### ISSUE TITLE
Figure out if additionalProperties in events are causing bugs

### ISSUE THREAD

**Issue by jsmnbom** [jsmnbom/definitelytyped-firefox-webext-browser#18]
See DefinitelyTyped/DefinitelyTyped#33171.
![image](https://user-images.githubusercontent.com/3002987/52977445-943f4f00-33cd-11e9-8523-4ca19efbde8d.png)
if not a bug with the parser, then report upstream maybe?

**Comment by josh-berry** [comment]
This is indeed causing bugs, because it leads to an incorrect definition for `browser.storage.onChanged`. [Your generated definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86303f134e12cf701a3f3f5e24867c3559351ea2/types/firefox-webext-browser/index.d.ts#L3195) is:

```ts
const onChanged: WebExtEvent<(changes: StorageChange, areaName: string) => void>;
```

And it should be something like:

```ts
const onChanged: WebExtEvent<(
    changes: {[key: string]: StorageChange},
    areaName: 'sync' | 'local' | 'managed'
) => void>;
```

From [the MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged), *changes* is supposed to be an object with arbitrary properties whose values are all `StorageChange` objects, something like:

```js
{
    foo: {oldValue: 1, newValue: 2},
    bar: {oldValue: "a", newValue: "b"}
}
```

**Comment by jsmnbom** [comment]
Thanks for reminding me that this was still an issue, I think I've found the culprit, should be fixed shortly :)
