### ISSUE TITLE
Generating types for Thunderbird

### ISSUE THREAD

**Issue by Juraj-Masiar** [jsmnbom/definitelytyped-firefox-webext-browser#39]
Could this be used to generate types also for Thunderbird?
I mean for the new WebExtension API in the new Thunderbird 78:
https://webextension-api.thunderbird.net/en/78/index.html
(it's mostly the same API but with some special namespaces for handling email related things)

**Comment by jsmnbom** [comment]
Depends on if mozilla is using the same Chrome-ish format for their schema files. Not something I personally have an interest in tho, but I'll keep the issue open in case anyone is wondering the same.

**Comment by JimDanner** [comment]
The library `@types/thunderbird-webext-browser` is now in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/thunderbird-webext-browser) and [npm](https://www.npmjs.com/package/@types/thunderbird-webext-browser). I [forked ](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser) this project and adjusted it to the Thunderbird WebExtension API.

@jsmnbom most of my edits have to do with the specifics of Thunderbird's schemas, but perhaps some may be useful for your project (or perhaps not). Specifically:

* Dealing with optional parameters in functions. That often means adding 'overloads', and I changed the algorithm for the creation of the overloads so it creates the smallest number of them. This also avoids some linting errors of type `unified-signatures`. My code is in [the second half of the `convertFunction` method](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L886-L933) of the `Converter` class.
* Hard-wrapping long lines in comments. This is mostly aesthetic, but it avoids `max-line-length` linting errors. It's in the same source file: I first [import a function from the `prettier` library](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L15) to do the wrapping, then use it in [two](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L180-L189) [places](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L1119-L1128) where comments are formatted. By the way, I also use it for [the final output](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L1164-L1179) of the program.
* Newlines in comments: to make sure `\n\n` in a description is translated into a double newline in the comment (which means a new paragraph in the mouse-over description in an IDE), I added [a line](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/desc-to-doc.ts#L73) to the `descToMarkdown` function. 
* I have nested the namespaces: instead of `declare namespace browser.accounts {...}` and `declare namespace browser.i18n {...}` and so on, I have `declare namespace browser {namespace accounts {...} namespace i18n {...} ...}`. The reasons have to do with, among other things, the way Visual Studio Code creates the help descriptions that show on mouse-over of a namespace. See [here](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/master/doc/Type%20files.md) for my findings on this. It is done with a few [small](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L315) [changes](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L955) in [four](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L1134) [places](https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser/blob/bb1940c6b2a28af14dadb4fe65b3b20795943ba4/src/converter.ts#L1151-L1157).

Other changes, like a more complicated download procedure, additional `export` keywords, and code to create a special version that works better in the WebStorm coding environment, are probably not very relevant for you.

**Comment by Juraj-Masiar** [comment]
Thank you Jim!
I've just tested in my Darko and ScrollAnywhere addons for Thunderbird and it works great! Great job!

**Comment by jsmnbom** [comment]
Gonna close this since @JimDanner 's fork fulfills this purpose ^^ https://github.com/JimDanner/definitelytyped-thunderbird-webext-browser

Thanks <3
