### ISSUE TITLE
`browser.identity.getAuthToken` resolves with `AccountInfo[]` instead of string

### ISSUE THREAD

**Issue by fregante** [jsmnbom/definitelytyped-firefox-webext-browser#41]
This is a Chrome-only API: https://developer.chrome.com/docs/extensions/reference/identity/#method-getAuthToken

Currently mistyped as 

```ts
    /**
     * Gets an OAuth2 access token using the client ID and scopes specified in the oauth2 section of manifest.json.
     * @deprecated Unsupported on Firefox at this time.
     */
    function getAuthToken(details?: _GetAuthTokenDetails): Promise<AccountInfo[]>;
```

It should be:

```ts
    function getAuthToken(details?: _GetAuthTokenDetails): Promise<string>;
```

**Comment by jsmnbom** [comment]
Yep, i see. Should be fixed when https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54359 merges ^^

**Comment by jsmnbom** [comment]
Oh nevermind, i misunderstood, gimme a sec.

**Comment by jsmnbom** [comment]
Hmm... not totally sure how to handle this one, since according to https://developer.chrome.com/docs/extensions/reference/identity/#method-getAuthToken, it can return two values?
Promise<string, string>, would be ideal, but that's obviously not possible...
Should i just put it as Promise<string> for now, and then we'll see how firefox solves the problem in the future and fix it then?

**Comment by fregante** [comment]
Indeed, perhaps it should just be removed for the time being because it's not part of the browser.* API

**Comment by fregante** [comment]
I moved to @types/chrome and @types/webextensions-polyfill
